import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./Header";

const inter = Inter({ subsets: ["latin"] });
import Image from "next/image";

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
          <link rel="stylesheet" href="https://horizon-tailwind-react-corporate-7s21b54hb-horizon-ui.vercel.app/static/css/main.d7f96858.css" />
      </head>
      <body>
        <main>
          <Header/>
          <div className="flex justify-center items-center justify-items-center">
            <Image className="" src={"/logo.png"} width={300} height={300}></Image>
          </div>
          {children}
        </main>
        
      </body>
    </html>
  );
}
